---
abstract: 'Algorithm::MOS - Calculate MOS (Mean Opinion Score)'
author:
  - 'Adam Balali <adamba@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-MOS
requires:
  Carp: 0
  Exporter: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.001
